---

  - apt: update_cache=yes

  - name: ensures that the required packages are present
    apt: name={{ item }} state=latest
    with_items:
      - mysql-client
      - python-pip
      - python-dev
      - libmysqlclient-dev
      - git

  - name: Ensures pyxis-api-django repo is cloned
    git: repo={{ repo }} dest={{ home }}/{{ repo_name }}
